//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VI.AOD.Segmentation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VI.AOD.Segmentation.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;colours&gt;&lt;tlo&gt;&lt;name&gt;tlo&lt;/name&gt;&lt;R&gt;255&lt;/R&gt;&lt;G&gt;255&lt;/G&gt;&lt;B&gt;255&lt;/B&gt;&lt;/tlo&gt;&lt;object1&gt;&lt;name&gt;object1&lt;/name&gt;&lt;R&gt;87&lt;/R&gt;&lt;G&gt;27&lt;/G&gt;&lt;B&gt;126&lt;/B&gt;&lt;/object1&gt;&lt;object2&gt;&lt;name&gt;object2&lt;/name&gt;&lt;R&gt;202&lt;/R&gt;&lt;G&gt;34&lt;/G&gt;&lt;B&gt;107&lt;/B&gt;&lt;/object2&gt;&lt;object3&gt;&lt;name&gt;object3&lt;/name&gt;&lt;R&gt;244&lt;/R&gt;&lt;G&gt;51&lt;/G&gt;&lt;B&gt;255&lt;/B&gt;&lt;/object3&gt;&lt;object4&gt;&lt;name&gt;object4&lt;/name&gt;&lt;R&gt;62&lt;/R&gt;&lt;G&gt;160&lt;/G&gt;&lt;B&gt;85&lt;/B&gt;&lt;/object4&gt;&lt;object5&gt;&lt;name&gt;object5&lt;/name&gt;&lt;R&gt;135&lt;/R&gt;&lt;G&gt;247&lt;/G&gt;&lt;B&gt;23&lt;/B&gt;&lt;/object5&gt;&lt;object6&gt;&lt;name&gt;object6&lt;/name&gt;&lt;R&gt;0&lt;/R&gt;&lt;G&gt;0&lt;/G&gt;&lt;B&gt;255&lt;/B&gt;&lt;/object6&gt;&lt;object7&gt;&lt;name&gt;object7&lt;/name&gt;&lt;R&gt;255&lt;/R&gt;&lt;G&gt;0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string colours {
            get {
                return ResourceManager.GetString("colours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fcnvgg {
            get {
                object obj = ResourceManager.GetObject("fcnvgg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] infer {
            get {
                object obj = ResourceManager.GetObject("infer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] LabelPainter {
            get {
                object obj = ResourceManager.GetObject("LabelPainter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] source_cityscapes {
            get {
                object obj = ResourceManager.GetObject("source_cityscapes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] upscale {
            get {
                object obj = ResourceManager.GetObject("upscale", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] utils {
            get {
                object obj = ResourceManager.GetObject("utils", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
